// <auto-generated />
using System;
using HogwardsApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HogwardsApp.Migrations
{
    [DbContext(typeof(HogwartsDbContext))]
    [Migration("20260721125546_AddWandsTable")]
    partial class AddWandsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HogwardsApp.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateTriggered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LogMessage")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK__AuditLog__3214EC072F746CE8");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("HogwardsApp.Models.HousePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateRecorded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("WizardId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__HousePoi__3214EC07E3B512F1");

                    b.HasIndex("SubjectId");

                    b.HasIndex("WizardId");

                    b.ToTable("HousePoints", t =>
                        {
                            t.HasTrigger("trg_ProtectGryffindor");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("HogwardsApp.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Teacher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Subjects__3214EC0728027920");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("HogwardsApp.Models.VGryffindorSquad", b =>
                {
                    b.Property<string>("BloodStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CoreMaterial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Core_Material");

                    b.Property<string>("GryffindorStudent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Gryffindor_Student");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("WandLength")
                        .HasColumnType("decimal(4, 1)")
                        .HasColumnName("Wand_Length");

                    b.ToTable((string)null);

                    b.ToView("v_GryffindorSquad", (string)null);
                });

            modelBuilder.Entity("HogwardsApp.Models.Wand", b =>
                {
                    b.Property<int>("WandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WandID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WandId"));

                    b.Property<string>("CoreMaterial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<int>("WizardId")
                        .HasColumnType("int");

                    b.HasKey("WandId")
                        .HasName("PK__Wands__BB49E3E85774A3C1");

                    b.HasIndex(new[] { "WizardId" }, "UQ_Wands_WizardId")
                        .IsUnique();

                    b.ToTable("Wands");
                });

            modelBuilder.Entity("HogwardsApp.Models.Wizard", b =>
                {
                    b.Property<int>("WizardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WizardId"));

                    b.Property<string>("BloodStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unknown", "DF_Wizards_BloodStatus");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("WizardId")
                        .HasName("PK__Wizards__EB46AA85B9AAC671");

                    b.HasIndex(new[] { "Name" }, "IX_Wizards_Name");

                    b.ToTable("Wizards");
                });

            modelBuilder.Entity("HogwardsApp.Models.vw_ActiveWizard", b =>
                {
                    b.Property<string>("BloodStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WizardId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_ActiveWizards", (string)null);
                });

            modelBuilder.Entity("HogwardsApp.Models.HousePoint", b =>
                {
                    b.HasOne("HogwardsApp.Models.Subject", "Subject")
                        .WithMany("HousePoints")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HousePoin__Subje__18EBB532");

                    b.HasOne("HogwardsApp.Models.Wizard", "Wizard")
                        .WithMany("HousePoints")
                        .HasForeignKey("WizardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HousePoin__Wizar__17F790F9");

                    b.Navigation("Subject");

                    b.Navigation("Wizard");
                });

            modelBuilder.Entity("HogwardsApp.Models.Wand", b =>
                {
                    b.HasOne("HogwardsApp.Models.Wizard", "Wizard")
                        .WithOne("Wand")
                        .HasForeignKey("HogwardsApp.Models.Wand", "WizardId")
                        .IsRequired()
                        .HasConstraintName("FK_Wands_Wizards");

                    b.Navigation("Wizard");
                });

            modelBuilder.Entity("HogwardsApp.Models.Subject", b =>
                {
                    b.Navigation("HousePoints");
                });

            modelBuilder.Entity("HogwardsApp.Models.Wizard", b =>
                {
                    b.Navigation("HousePoints");

                    b.Navigation("Wand");
                });
#pragma warning restore 612, 618
        }
    }
}
